research_chapter:
  description: >
    Research specific information for the chapter titled "{chapter_title}".
    Focus on gathering detailed, practical, and scientifically-backed information about "{topic}".

    IMPORTANT: When using the search tool, use English keywords to get better results.
    Translate the chapter title and main concepts to English for searching.

    Chapter Description: {chapter_description}
    Target Audience: {target_audience}
    Book Goal: {goal}
  expected_output: >
    Detailed research findings specific to the chapter, including:
    - Key concepts and definitions
    - Practical examples and applications
    - Current trends and best practices
    - Supporting evidence and sources
  agent: researcher

write_chapter:
  description: >
    Write a well-structured chapter based on the chapter title and outline description.
    Each chapter should be written in markdown and should contain around 3,000 words.

    Topic: {topic}
    Chapter Title: {chapter_title}
    Chapter Description: {chapter_description}
    Target Audience: {target_audience}

    IMPORTANT: Generate all content in Portuguese (pt-BR).
    Even though you receive instructions in English, all your outputs must be in Portuguese.
  expected_output: >
    A markdown-formatted chapter that includes:
    - Clear introduction
    - Well-structured content (around 3,000 words)
    - Practical examples and applications
    - Summary or key takeaways
    - All content in Portuguese (pt-BR)
  agent: writer 